routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
\Illuminate\Support\Facades\Artisan::call('storage:link');
Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function() {

    Route::get('/', function () {
        return view('blades.index');
    });


    Route::get("/","indexController@index");
    Route::get("CategoryProduct-{id}","indexController@CategoryProduct")->name('cat.product');
    Route::get("Product-{id}","indexController@Product")->name('product')->name('product.single');
    Route::get("AllProducts","indexController@allproduct")->name('all.products');

    Route::get("Blog-{id}","indexController@getblog");
//Route::get("category/{id}","indexController@Product")->name('category.product');
//Route::post("Product-{id}","cartController@addcart");

    Route::delete('/products/{id}', 'productController@delFromCart')->name('product.remove');
    Route::put('/products/{product}', 'ProductController@updateCart')->name('product.update');
    Route::delete('delete_product/{product}','cartController@delete_product')->name('cart.delete');

    Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('cart.add');
    Route::get('/shopping-cart', 'ProductController@showCart')->name('cart');
    Route::get("Contactus","indexController@Contactus");
    Route::post("Contactus","ContactusController@store");

    Route::get("Aboutus","indexController@aboutus");



// Route::get('RegisterLogin', function () {
//     return view('blades.loginandregister');
// });





    Route::get('/home', 'HomeController@index');

    Auth::routes();

    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
    Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
    Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
    Route::post('generator_builder/generate-from-file','\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');



    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::group(['middleware' => ['auth', 'auth.admin']], function() {
        Route::prefix('admin')->group(function () {
            Route::get('/', 'HomeController@index');

            Route::resource('brands', 'BrandController');

            Route::resource('categories', 'CategoryController');

            Route::resource('products', 'ProductController');

            Route::resource('ads', 'AdsController');

            Route::resource('footerAds', 'FooterAdsController');

            Route::resource('sliders', 'SliderController');

            Route::resource('productGalleries', 'ProductGalleryController');

            Route::resource('productGalleries', 'ProductGalleryController');

            Route::resource('sizes', 'SizeController');

            Route::resource('colors', 'ColorController');

            Route::resource('stocks', 'stockController');



            Route::resource('roles', 'RoleController');
        });
    });

    Route::resource('accounts', 'accountController');

    Route::resource('orders', 'OrderController');

    Route::resource('statics', 'StaticsController');

    Route::resource('galleries', 'GalleryController');

    Route::resource('blogs', 'BlogsController');

    Route::resource('contactuses', 'ContactusController');



    Route::post('checkout','OrderController@add_account_and_order')->name('checkout');

});

Route::post('/add_to_cart','cartController@store');

app/Models/FooterAds.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class FooterAds
 * @package App\Models
 * @version January 23, 2020, 6:32 am UTC
 *
 * @property string text
 * @property string image
 */
class FooterAds extends Model
{

    public $table = 'footer_ads';
    



    public $fillable = [
        'link',
        'image'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'text' => 'string',
        'image' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/FooterAdsController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\FooterAdsDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateFooterAdsRequest;
use App\Http\Requests\UpdateFooterAdsRequest;
use App\Repositories\FooterAdsRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class FooterAdsController extends AppBaseController
{
    /** @var  FooterAdsRepository */
    private $footerAdsRepository;

    public function __construct(FooterAdsRepository $footerAdsRepo)
    {
        $this->footerAdsRepository = $footerAdsRepo;
    }

    /**
     * Display a listing of the FooterAds.
     *
     * @param FooterAdsDataTable $footerAdsDataTable
     * @return Response
     */
    public function index(FooterAdsDataTable $footerAdsDataTable)
    {
        return $footerAdsDataTable->render('footer_ads.index');
    }

    /**
     * Show the form for creating a new FooterAds.
     *
     * @return Response
     */
    public function create()
    {
        return view('footer_ads.create');
    }

    /**
     * Store a newly created FooterAds in storage.
     *
     * @param CreateFooterAdsRequest $request
     *
     * @return Response
     */
    public function store(CreateFooterAdsRequest $request)
    {
        $input = $request->all();

        $footerAds = $this->footerAdsRepository->create($input);

        Flash::success('Footer Ads saved successfully.');

        return redirect(route('footerAds.index'));
    }

    /**
     * Display the specified FooterAds.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $footerAds = $this->footerAdsRepository->find($id);

        if (empty($footerAds)) {
            Flash::error('Footer Ads not found');

            return redirect(route('footerAds.index'));
        }

        return view('footer_ads.show')->with('footerAds', $footerAds);
    }

    /**
     * Show the form for editing the specified FooterAds.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $footerAds = $this->footerAdsRepository->find($id);

        if (empty($footerAds)) {
            Flash::error('Footer Ads not found');

            return redirect(route('footerAds.index'));
        }

        return view('footer_ads.edit')->with('footerAds', $footerAds);
    }

    /**
     * Update the specified FooterAds in storage.
     *
     * @param  int              $id
     * @param UpdateFooterAdsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFooterAdsRequest $request)
    {
        $footerAds = $this->footerAdsRepository->find($id);

        if (empty($footerAds)) {
            Flash::error('Footer Ads not found');

            return redirect(route('footerAds.index'));
        }

        $footerAds = $this->footerAdsRepository->update($request->all(), $id);

        Flash::success('Footer Ads updated successfully.');

        return redirect(route('footerAds.index'));
    }

    /**
     * Remove the specified FooterAds from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $footerAds = $this->footerAdsRepository->find($id);

        if (empty($footerAds)) {
            Flash::error('Footer Ads not found');

            return redirect(route('footerAds.index'));
        }

        $this->footerAdsRepository->delete($id);

        Flash::success('Footer Ads deleted successfully.');

        return redirect(route('footerAds.index'));
    }
}

resources/views/footer_ads/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('footerAds.index') !!}">Footer Ads</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Footer Ads</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'footerAds.store', 'files' => true]) !!}

                                   @include('footer_ads.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/footer_ads/datatables_actions.blade.php
{!! Form::open(['route' => ['footerAds.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('footerAds.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('footerAds.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/footer_ads/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('footerAds.index') !!}">Footer Ads</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Footer Ads</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($footerAds, ['route' => ['footerAds.update', $footerAds->id], 'method' => 'patch', 'files' => true]) !!}

                              @include('footer_ads.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/footer_ads/fields.blade.php
<!-- Text Field -->
<div class="form-group col-sm-6">
    {!! Form::label('text', 'Text:') !!}
    {!! Form::text('text', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image') !!}
</div>
<div class="clearfix"></div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('footerAds.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/footer_ads/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Footer Ads</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             FooterAds
                             <a class="pull-right" href="{{ route('footerAds.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('footer_ads.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/footer_ads/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('footerAds.index') }}">Footer Ads</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('footerAds.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('footer_ads.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/footer_ads/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $footerAds->id }}</p>
</div>

<!-- Text Field -->
<div class="form-group">
    {!! Form::label('text', 'Text:') !!}
    <p>{{ $footerAds->text }}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{{ $footerAds->image }}</p>
</div>

resources/views/footer_ads/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection