routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
\Illuminate\Support\Facades\Artisan::call('storage:link');
Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function() {

    Route::get('/', function () {
        return view('blades.index');
    });


    Route::get("/","indexController@index");
    Route::get("CategoryProduct-{id}","indexController@CategoryProduct")->name('cat.product');
    Route::get("Product-{id}","indexController@Product")->name('product')->name('product.single');
    Route::get("AllProducts","indexController@allproduct")->name('all.products');

    Route::get("Blog-{id}","indexController@getblog");
//Route::get("category/{id}","indexController@Product")->name('category.product');
//Route::post("Product-{id}","cartController@addcart");

    Route::delete('/products/{id}', 'productController@delFromCart')->name('product.remove');
    Route::put('/products/{product}', 'ProductController@updateCart')->name('product.update');
    Route::delete('delete_product/{product}','cartController@delete_product')->name('cart.delete');

    Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('cart.add');
    Route::get('/shopping-cart', 'ProductController@showCart')->name('cart');
    Route::get("Contactus","indexController@Contactus");
    Route::post("Contactus","ContactusController@store");

    Route::get("Aboutus","indexController@aboutus");



// Route::get('RegisterLogin', function () {
//     return view('blades.loginandregister');
// });





    Route::get('/home', 'HomeController@index');

    Auth::routes();

    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
    Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
    Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
    Route::post('generator_builder/generate-from-file','\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');



    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::group(['middleware' => ['auth', 'auth.admin']], function() {
        Route::prefix('admin')->group(function () {
            Route::get('/', 'HomeController@index');

            Route::resource('brands', 'BrandController');

            Route::resource('categories', 'CategoryController');

            Route::resource('products', 'ProductController');

            Route::resource('ads', 'AdsController');

            Route::resource('footerAds', 'FooterAdsController');

            Route::resource('sliders', 'SliderController');

            Route::resource('productGalleries', 'ProductGalleryController');

            Route::resource('productGalleries', 'ProductGalleryController');

            Route::resource('sizes', 'SizeController');

            Route::resource('colors', 'ColorController');

            Route::resource('stocks', 'stockController');



            Route::resource('roles', 'RoleController');
        });
    });

    Route::resource('accounts', 'accountController');

    Route::resource('orders', 'OrderController');

    Route::resource('statics', 'StaticsController');

    Route::resource('galleries', 'GalleryController');

    Route::resource('blogs', 'BlogsController');

    Route::resource('contactuses', 'ContactusController');



    Route::post('checkout','OrderController@add_account_and_order')->name('checkout');

});

Route::post('/add_to_cart','cartController@store');

app/Models/ProductGallery.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class ProductGallery
 * @package App\Models
 * @version January 23, 2020, 9:42 am UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection products
 * @property string image
 * @property integer product_id
 */
class ProductGallery extends Model
{

    public $table = 'product_galleries';
    
public $timestamps=false;


    public $fillable = [
        'image',
        'product_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'image' => 'string',
        'product_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function products()
    {
        return $this->belongsTo(\App\Models\product::class, 'product_id', 'id');
    }
}

app/Http/Controllers/ProductGalleryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProductGalleryDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateProductGalleryRequest;
use App\Http\Requests\UpdateProductGalleryRequest;
use App\Repositories\ProductGalleryRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Models\Product;
use Response;

class ProductGalleryController extends AppBaseController
{
    /** @var  ProductGalleryRepository */
    private $productGalleryRepository;

    public function __construct(ProductGalleryRepository $productGalleryRepo)
    {
        $this->productGalleryRepository = $productGalleryRepo;
    }

    /**
     * Display a listing of the ProductGallery.
     *
     * @param ProductGalleryDataTable $productGalleryDataTable
     * @return Response
     */
    public function index(ProductGalleryDataTable $productGalleryDataTable)
    {
        return $productGalleryDataTable->render('product_galleries.index');
    }

    /**
     * Show the form for creating a new ProductGallery.
     *
     * @return Response
     */
    public function create()
    {
        $product= Product::pluck('name','id');
        return view('product_galleries.create')->with('product',$product);
    }

    /**
     * Store a newly created ProductGallery in storage.
     *
     * @param CreateProductGalleryRequest $request
     *
     * @return Response
     */
    public function store(CreateProductGalleryRequest $request)
    {
        $input = $request->all();
        $File=$request-> file('image');
        $destination= '/images';
        $newfile = rand(1, 999) . $File -> getClientOriginalName();
        $File ->move ($destination , $newfile);
        $input['image'] = $newfile;


        $productGallery = $this->productGalleryRepository->create($input);

        Flash::success('Product Gallery saved successfully.');

        return redirect(route('productGalleries.index'));
    }

    /**
     * Display the specified ProductGallery.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $productGallery = $this->productGalleryRepository->find($id);

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        return view('product_galleries.show')->with('productGallery', $productGallery);
    }

    /**
     * Show the form for editing the specified ProductGallery.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $productGallery = $this->productGalleryRepository->find($id);
        $product= Product::pluck('name','id');

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        return view('product_galleries.edit')->with('productGallery', $productGallery)->with('product',$product);
    }

    /**
     * Update the specified ProductGallery in storage.
     *
     * @param  int              $id
     * @param UpdateProductGalleryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductGalleryRequest $request)
    {
        $productGallery = $this->productGalleryRepository->find($id);


        $gall=$request->all();
        if($request->hasFile('image')) {
        $File=$request-> file('image');
        $destination= '/images';
        $newfile = rand(1, 999) . $File -> getClientOriginalName();
        $File ->move ($destination , $newfile);
        $gall["image"]= $newfile;
        }

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        $productGallery = $this->productGalleryRepository->update($gall, $id);

        Flash::success('Product Gallery updated successfully.');

        return redirect(route('productGalleries.index'));
    }

    /**
     * Remove the specified ProductGallery from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $productGallery = $this->productGalleryRepository->find($id);

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        $this->productGalleryRepository->delete($id);

        Flash::success('Product Gallery deleted successfully.');

        return redirect(route('productGalleries.index'));
    }
}

resources/views/product_galleries/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('productGalleries.index') !!}">Product Gallery</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Product Gallery</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'productGalleries.store', 'files' => true]) !!}

                                   @include('product_galleries.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/product_galleries/datatables_actions.blade.php
{!! Form::open(['route' => ['productGalleries.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('productGalleries.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('productGalleries.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/product_galleries/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('productGalleries.index') !!}">Product Gallery</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Product Gallery</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($productGallery, ['route' => ['productGalleries.update', $productGallery->id], 'method' => 'patch', 'files' => true]) !!}

                              @include('product_galleries.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/product_galleries/fields.blade.php
<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image') !!}
</div>
<div class="clearfix"></div>

<!-- Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product', 'Product:') !!}
   
    {!! Form::select('product_id', ['product' => $product], null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('productGalleries.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/product_galleries/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Product Galleries</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             ProductGalleries
                             <a class="pull-right" href="{{ route('productGalleries.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('product_galleries.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/product_galleries/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('productGalleries.index') }}">Product Gallery</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('productGalleries.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('product_galleries.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/product_galleries/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $productGallery->id }}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <img src="{{asset('images/'.$productGallery->image)}}" style="width:30%">
</div>

<!-- Product Id Field -->
<div class="form-group">
    {!! Form::label('product', 'Product :') !!}
    <p>{{ $productGallery->products->name }}</p>

</div>

resources/views/product_galleries/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection