routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
\Illuminate\Support\Facades\Artisan::call('storage:link');
Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function() {

    Route::get('/', function () {
        return view('blades.index');
    });


    Route::get("/","indexController@index");
    Route::get("CategoryProduct-{id}","indexController@CategoryProduct")->name('cat.product');
    Route::get("Product-{id}","indexController@Product")->name('product')->name('product.single');
    Route::get("AllProducts","indexController@allproduct")->name('all.products');

    Route::get("Blog-{id}","indexController@getblog");
//Route::get("category/{id}","indexController@Product")->name('category.product');
//Route::post("Product-{id}","cartController@addcart");

    Route::delete('/products/{id}', 'productController@delFromCart')->name('product.remove');
    Route::put('/products/{product}', 'ProductController@updateCart')->name('product.update');
    Route::delete('delete_product/{product}','cartController@delete_product')->name('cart.delete');

    Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('cart.add');
    Route::get('/shopping-cart', 'ProductController@showCart')->name('cart');
    Route::get("Contactus","indexController@Contactus");
    Route::post("Contactus","ContactusController@store");

    Route::get("Aboutus","indexController@aboutus");



// Route::get('RegisterLogin', function () {
//     return view('blades.loginandregister');
// });





    Route::get('/home', 'HomeController@index');

    Auth::routes();

    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
    Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
    Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
    Route::post('generator_builder/generate-from-file','\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');



    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::group(['middleware' => ['auth', 'auth.admin']], function() {
        Route::prefix('admin')->group(function () {
            Route::get('/', 'HomeController@index');

            Route::resource('brands', 'BrandController');

            Route::resource('categories', 'CategoryController');

            Route::resource('products', 'ProductController');

            Route::resource('ads', 'AdsController');

            Route::resource('footerAds', 'FooterAdsController');

            Route::resource('sliders', 'SliderController');

            Route::resource('productGalleries', 'ProductGalleryController');

            Route::resource('productGalleries', 'ProductGalleryController');

            Route::resource('sizes', 'SizeController');

            Route::resource('colors', 'ColorController');

            Route::resource('stocks', 'stockController');



            Route::resource('roles', 'RoleController');
        });
    });

    Route::resource('accounts', 'accountController');

    Route::resource('orders', 'OrderController');

    Route::resource('statics', 'StaticsController');

    Route::resource('galleries', 'GalleryController');

    Route::resource('blogs', 'BlogsController');

    Route::resource('contactuses', 'ContactusController');



    Route::post('checkout','OrderController@add_account_and_order')->name('checkout');

});

Route::post('/add_to_cart','cartController@store');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{config('app.name')}}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 4.1.1 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://unpkg.com/@coreui/icons/css/coreui-icons.min.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">

        <img class="navbar-brand-full" src="{{asset('assets/images/logo.png')}}" width="30" height="30"
             alt=" Logo">
        <img class="navbar-brand-minimized" src="{{asset('assets/images/logo.png')}}" width="30"
             height="30" alt="Logo">

    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav ml-auto">

        <li class="nav-item dropdown">
            <a class="nav-link" style="margin-right: 10px" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                {{ Auth::user()->name }}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <!-- <a class="dropdown-item" href="#">
                    <i class="fa fa-envelope-o"></i> Messages
                    <span class="badge badge-success">42</span>
                </a>
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-user"></i> Profile</a>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-wrench"></i> Settings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-shield"></i> Lock Account</a> -->
                <a href="{{ url('/logout') }}" class="dropdown-item btn btn-default btn-flat"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i>Logout
                </a>
                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</header>

<div class="app-body">
    @include('layouts.sidebar')
    <main class="main">
        @yield('content')
    </main>
</div>
<footer class="app-footer">
    <div>
        <a href="https://infyom.com">Infyom </a>
        <span>&copy; 2019 infyomLabs.</span>
    </div>
    <div class="ml-auto">
        <span>Powered by</span>
        <a href="https://coreui.io">CoreUI</a>
    </div>
</footer>
</body>
<!-- jQuery 3.1.1 -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>

@yield('scripts')

</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<!-- <li class="nav-item {{ Request::is('brands*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('brands.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Brands</span>
    </a>
</li> -->
<li class="nav-item {{ Request::is('categories*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('categories.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Categories</span>
    </a>
</li>

<li class="nav-item {{ Request::is('products*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('products.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Products</span>
    </a>
</li>
<!-- <li class="nav-item {{ Request::is('ads*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('ads.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Ads</span>
    </a>
</li> -->
<!-- <li class="nav-item {{ Request::is('footerAds*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('footerAds.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Footer Ads</span>
    </a>
</li> -->
<li class="nav-item {{ Request::is('sliders*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('sliders.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Sliders</span>
    </a>
</li>
<li class="nav-item {{ Request::is('productGalleries*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('productGalleries.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Product Galleries</span>
    </a>
</li>
<!-- <li class="nav-item {{ Request::is('sizes*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('sizes.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Sizes</span>
    </a>
</li>
<li class="nav-item {{ Request::is('colors*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('colors.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Colors</span>
    </a>
</li> -->
<!-- <li class="nav-item {{ Request::is('stocks*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('stocks.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Stocks</span>
    </a>
</li> -->
<!-- <li class="nav-item {{ Request::is('roles*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('roles.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Roles</span>
    </a>
</li> -->
<li class="nav-item {{ Request::is('accounts*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('accounts.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Orders Details</span>
    </a>
</li>
<li class="nav-item {{ Request::is('orders*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('orders.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Orders</span>
    </a>
</li>
<li class="nav-item {{ Request::is('statics*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('statics.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Statics</span>
    </a>
</li>
<!-- <li class="nav-item {{ Request::is('galleries*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('galleries.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Galleries</span>
    </a>
</li> -->
<li class="nav-item {{ Request::is('blogs*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('blogs.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Blogs</span>
    </a>
</li>
<li class="nav-item {{ Request::is('contactuses*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('contactuses.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Contactuses</span>
    </a>
</li>

resources/views/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            @include('layouts.menu')
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>